### ISSUE TITLE
An unexpected error occurred: "expected hoisted manifest for \"tailwindcss#color\"".

### ISSUE THREAD

**Issue by sumeetadur** [tailwindlabs/tailwindcss-aspect-ratio#35] opened 2023-01-09 11:05 UTC
### What version of @tailwindcss/aspect-ratio are you using?

v0.4.2

### What version of Node.js are you using?

v14.19.1

### What browser are you using?

Brave

### What operating system are you using?

macOS

### Reproduction repository

N/A

### Describe your issue

$ yarn add -D @tailwindcss/aspect-ratio
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error An unexpected error occurred: "expected hoisted manifest for \"tailwindcss#color\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/sumeetadur/Projects/remote-tech/com.l8log.web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by adamwathan** [comment] 2023-01-13 15:58
Going to close this since a reproduction was not provided, but if this is still an issue for you don't hesitate to open a new issue that includes a reproduction 👍

**Closed by adamwathan** 2023-01-13 15:58 UTC
